# Generated by Django 2.2.7 on 2021-05-14 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 17, 13, 13, 354519, tzinfo=utc))),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 17, 13, 13, 354519, tzinfo=utc))),
                ('total', models.CharField(max_length=20)),
                ('active', models.CharField(max_length=20)),
                ('death', models.CharField(max_length=20)),
                ('recovered', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NonVerifiedLead',
            fields=[
                ('Id', models.CharField(default='id', max_length=120, primary_key=True, serialize=False)),
                ('Supplier', models.CharField(blank=True, max_length=50)),
                ('Resource', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('Remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedLead',
            fields=[
                ('Timestamp', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 17, 13, 13, 354519, tzinfo=utc))),
                ('Id', models.CharField(default='id', max_length=120, primary_key=True, serialize=False)),
                ('Supplier', models.CharField(blank=True, max_length=50)),
                ('Resource', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('Remarks', models.TextField(blank=True)),
            ],
        ),
    ]
